import { route } from 'ziggy-js';

// Exportar la configuración de rutas de Laravel
const Ziggy = {
    url: 'http://localhost',
    port: null,
    defaults: {},
    routes: {
        "logout":{"uri":"logout","methods":["POST"]},
        "password.email":{"uri":"forgot-password","methods":["POST"]},
        "password.update":{"uri":"reset-password","methods":["POST"]},
        "verification.verify":{"uri":"verify-email\/{id}\/{hash}","methods":["GET","HEAD"],"parameters":["id","hash"]},
        "verification.send":{"uri":"email\/verification-notification","methods":["POST"]},
        "user-profile-information.update":{"uri":"user\/profile-information","methods":["PUT"]},
        "user-password.update":{"uri":"user\/password","methods":["PUT"]},
        "password.confirmation":{"uri":"user\/confirmed-password-status","methods":["GET","HEAD"]},
        "password.confirm.store":{"uri":"user\/confirm-password","methods":["POST"]},
        "two-factor.login.store":{"uri":"two-factor-challenge","methods":["POST"]},
        "two-factor.enable":{"uri":"user\/two-factor-authentication","methods":["POST"]},
        "two-factor.confirm":{"uri":"user\/confirmed-two-factor-authentication","methods":["POST"]},
        "two-factor.disable":{"uri":"user\/two-factor-authentication","methods":["DELETE"]},
        "two-factor.qr-code":{"uri":"user\/two-factor-qr-code","methods":["GET","HEAD"]},
        "two-factor.secret-key":{"uri":"user\/two-factor-secret-key","methods":["GET","HEAD"]},
        "two-factor.recovery-codes":{"uri":"user\/two-factor-recovery-codes","methods":["GET","HEAD"]},
        "profile.show":{"uri":"user\/profile","methods":["GET","HEAD"]},
        "other-browser-sessions.destroy":{"uri":"user\/other-browser-sessions","methods":["DELETE"]},
        "current-user-photo.destroy":{"uri":"user\/profile-photo","methods":["DELETE"]},
        "current-user.destroy":{"uri":"user","methods":["DELETE"]},
        "sanctum.csrf-cookie":{"uri":"sanctum\/csrf-cookie","methods":["GET","HEAD"]},
        "livewire.update":{"uri":"livewire\/update","methods":["POST"]},
        "livewire.upload-file":{"uri":"livewire\/upload-file","methods":["POST"]},
        "livewire.preview-file":{"uri":"livewire\/preview-file\/{filename}","methods":["GET","HEAD"],"parameters":["filename"]},
        "seo.analyze":{"uri":"seo\/analyze","methods":["POST"]},
        "seo.analysis.status":{"uri":"api\/seo\/analysis\/{id}","methods":["GET","HEAD"],"parameters":["id"]},
        "services":{"uri":"services","methods":["GET","HEAD"]},
        "services.show":{"uri":"services\/{service}","methods":["GET","HEAD"],"parameters":["service"],"bindings":{"service":"id"}},
        "portfolio":{"uri":"portfolio","methods":["GET","HEAD"]},
        "portfolio.show":{"uri":"portfolio\/{project}","methods":["GET","HEAD"],"parameters":["project"],"bindings":{"project":"id"}},
        "contact":{"uri":"contact","methods":["GET","HEAD"]},
        "contact.store":{"uri":"contact","methods":["POST"]},
        "skills.show":{"uri":"skills\/{skill}","methods":["GET","HEAD"],"parameters":["skill"],"bindings":{"skill":"id"}},
        "seo.dashboard":{"uri":"seo\/dashboard","methods":["GET","HEAD"]},
        "projects.index":{"uri":"projects","methods":["GET","HEAD"]},
        "projects.create":{"uri":"projects\/create","methods":["GET","HEAD"]},
        "projects.store":{"uri":"projects","methods":["POST"]},
        "seo.projects.show":{"uri":"seo\/projects\/{project}","methods":["GET","HEAD"],"parameters":["project"],"bindings":{"project":"id"}},
        "seo.projects.edit":{"uri":"seo\/projects\/{project}\/edit","methods":["GET","HEAD"],"parameters":["project"],"bindings":{"project":"id"}},
        "projects.update":{"uri":"projects\/{project}","methods":["PUT","PATCH"],"parameters":["project"],"bindings":{"project":"id"}},
        "projects.destroy":{"uri":"projects\/{project}","methods":["DELETE"],"parameters":["project"],"bindings":{"project":"id"}},
        "seo.projects.stats":{"uri":"seo\/projects\/{project}\/stats","methods":["GET","HEAD"],"parameters":["project"],"bindings":{"project":"id"}},
        "seo.projects.history":{"uri":"seo\/projects\/{project}\/history","methods":["GET","HEAD"],"parameters":["project"],"bindings":{"project":"id"}},
        "seo.projects.import":{"uri":"seo\/projects\/import","methods":["POST"]},
        "seo.projects.export":{"uri":"seo\/projects\/export","methods":["GET","HEAD"]},
        "seo.keywords.index":{"uri":"seo\/keywords","methods":["GET","HEAD"]},
        "seo.keywords.store":{"uri":"seo\/keywords","methods":["POST"]},
        "seo.keywords.show":{"uri":"seo\/keywords\/{keyword}","methods":["GET","HEAD"],"parameters":["keyword"]},
        "seo.keywords.destroy":{"uri":"seo\/keywords\/{keyword}","methods":["DELETE"],"parameters":["keyword"]},
        "seo.keywords.dataforseo":{"uri":"seo\/keywords\/dataforseo","methods":["POST"]},
        "rank-tracker.index":{"uri":"seo\/rank-tracker","methods":["GET","HEAD"]},
        "rank-tracker.store":{"uri":"seo\/rank-tracker\/store","methods":["POST"]},
        "rank-tracker.history":{"uri":"seo\/rank-tracker\/history","methods":["GET","HEAD"]},
        "seo.analysis.get":{"uri":"seo\/analysis\/{id}","methods":["GET","HEAD"],"parameters":["id"]},
        "seo.ubersuggest.index":{"uri":"seo\/ubersuggest","methods":["GET","HEAD"]},
        "seo.ubersuggest.suggest":{"uri":"seo\/ubersuggest\/suggest","methods":["POST"]},
        "seo.meta-tags.index":{"uri":"seo\/meta-tags","methods":["GET","HEAD"]},
        "seo.meta-tags.analyze":{"uri":"seo\/meta-tags\/analyze","methods":["POST"]},
        "login":{"uri":"login","methods":["GET","HEAD"]},
        "register":{"uri":"register","methods":["GET","HEAD"]},
        "dashboard":{"uri":"dashboard","methods":["GET","HEAD"]},
        "profile.edit":{"uri":"profile","methods":["GET","HEAD"]},
        "profile.update":{"uri":"profile","methods":["PATCH"]},
        "profile.destroy":{"uri":"profile","methods":["DELETE"]},
        "tools.web-traffic.index":{"uri":"tools\/web-traffic","methods":["GET","HEAD"]},
        "tools.web-traffic.show":{"uri":"tools\/web-traffic\/{project}","methods":["GET","HEAD"],"parameters":["project"],"bindings":{"project":"id"}},
        "tools.seo.meta-tags.index":{"uri":"tools\/seo-meta-tags","methods":["GET","HEAD"]},
        "tools.seo.meta-tags.show":{"uri":"tools\/seo-meta-tags\/{project}","methods":["GET","HEAD"],"parameters":["project"],"bindings":{"project":"id"}},
        "tools.seo.meta-tags.analyze":{"uri":"tools\/seo-meta-tags\/{project}\/analyze","methods":["POST"],"parameters":["project"],"bindings":{"project":"id"}},
        "tools.paid-ads.index":{"uri":"tools\/paid-ads","methods":["GET","HEAD"]},
        "tools.paid-ads.show":{"uri":"tools\/paid-ads\/{project}","methods":["GET","HEAD"],"parameters":["project"],"bindings":{"project":"id"}},
        "tools.paid-ads.generate":{"uri":"tools\/paid-ads\/{project}\/generate","methods":["POST"],"parameters":["project"],"bindings":{"project":"id"}},
        "tools.social-media.index":{"uri":"tools\/social-media","methods":["GET","HEAD"]},
        "tools.social-media.show":{"uri":"tools\/social-media\/{project}","methods":["GET","HEAD"],"parameters":["project"],"bindings":{"project":"id"}},
        "tools.social-media.generate":{"uri":"tools\/social-media\/{project}\/generate","methods":["POST"],"parameters":["project"],"bindings":{"project":"id"}},
        "projects.show":{"uri":"projects\/{project}","methods":["GET","HEAD"],"parameters":["project"],"bindings":{"project":"id"}},
        "projects.edit":{"uri":"projects\/{project}\/edit","methods":["GET","HEAD"],"parameters":["project"],"bindings":{"project":"id"}},
        "seo.backlink-prices.index":{"uri":"seo\/backlink-prices","methods":["GET","HEAD"]},
        "seo.backlink-prices.store":{"uri":"seo\/backlink-prices","methods":["POST"]},
        "seo.backlink-prices.compare":{"uri":"seo\/backlink-prices\/compare","methods":["GET","HEAD"]},
        "answer-the-public":{"uri":"answer-the-public","methods":["GET","HEAD"]},
        "answer-the-public.suggestions":{"uri":"answer-the-public\/suggestions","methods":["POST"]},
        "ab-test.index":{"uri":"ab-test","methods":["GET","HEAD"]},
        "ab-test.calculate":{"uri":"ab-test\/calculate","methods":["POST"]},
        "ads.analyze":{"uri":"ads\/analyze","methods":["POST"]},
        "ads.history":{"uri":"ads\/history","methods":["GET","HEAD"]},
        "ads.ads-grader.index":{"uri":"ads\/ads-grader","methods":["GET","HEAD"]},
        "ads.ads-grader.analyze":{"uri":"ads\/ads-grader\/analyze","methods":["POST"]},
        "ads.ads-grader.history":{"uri":"ads\/ads-grader\/history","methods":["GET","HEAD"]},
        "mail.grader.index":{"uri":"mail\/grader","methods":["GET","HEAD"]},
        "mail.grader.analyze":{"uri":"mail\/grader\/analyze","methods":["POST"]},
        "ai-writer":{"uri":"ai-writer","methods":["GET","HEAD"]},
        "social-media.index":{"uri":"social-media","methods":["GET","HEAD"]},
        "social-media.generate":{"uri":"social-media\/generate","methods":["POST"]},
        "social-media.schedule":{"uri":"social-media\/schedule","methods":["POST"]},
        "paid-ads.index":{"uri":"paid-ads","methods":["GET","HEAD"]},
        "paid-ads.generate":{"uri":"paid-ads\/generate","methods":["POST"]},
        "password.request":{"uri":"forgot-password","methods":["GET","HEAD"]},
        "password.reset":{"uri":"reset-password\/{token}","methods":["GET","HEAD"],"parameters":["token"]},
        "verification.notice":{"uri":"verify-email","methods":["GET","HEAD"]},
        "password.confirm":{"uri":"confirm-password","methods":["GET","HEAD"]}
    }
};

// Si hay rutas definidas en el servidor, combinarlas
if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    Object.assign(Ziggy.routes, window.Ziggy.routes);
}

export { Ziggy, route };

// Hacer que la función route esté disponible globalmente
if (typeof window !== 'undefined') {
    window.Ziggy = Ziggy;
    window.route = (name, params, absolute) => route(name, params, absolute, Ziggy);
}
